apiVersion: apps/v1
kind: Deployment
metadata:
  name: cuota-deployment
  labels:
    app: cuota-deployment
spec:
  selector:
    matchLabels:
      app: cuota-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: cuota-deployment
    spec:
      containers:
        - name: kubernetes-cuota
          image: jvergara1609/kubernetes-cuota:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service:8081
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-service:8761
            - name: eureka.instance.preferIpAddress
              value: "true"
            - name: MYSQL_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: MYSQL_DB_HOST
            - name: MYSQL_DB_CUOTA
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: MYSQL_DB_CUOTA
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-root-credentials
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root-credentials
                  key: MYSQL_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: cuota-service
  labels:
    app: cuota-service
spec:
  selector:
    app: cuota-deployment
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: LoadBalancer