apiVersion: apps/v1
kind: Deployment
metadata:
  name: estudiante-deployment
  labels:
    app: estudiante-deployment
spec:
  selector:
    matchLabels:
      app: estudiante-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: estudiante-deployment
    spec:
      containers:
        - name: kubernetes-estudiante
          image: jvergara1609/kubernetes-estudiante:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service:8081
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-service:8761
            - name: eureka.instance.preferIpAddress
              value: "true"
            - name: MYSQL_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: MYSQL_DB_HOST
            - name: MYSQL_DB_ESTUDIANTE
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: MYSQL_DB_ESTUDIANTE
            - name: MYSQL_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-root-credentials
                  key: MYSQL_ROOT_USER
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root-credentials
                  key: MYSQL_ROOT_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: estudiante-service
  labels:
    app: estudiante-service
spec:
  selector:
    app: estudiante-deployment
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: LoadBalancer