apiVersion: apps/v1
kind: Deployment
metadata:
  name: planilla-deployment
  labels:
    app: planilla-deployment
spec:
  selector:
    matchLabels:
      app: planilla-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: planilla-deployment
    spec:
      containers:
        - name: kubernetes-planilla
          image: jvergara1609/kubernetes-planilla:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service:8081
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-service:8761
            - name: eureka.instance.preferIpAddress
              value: "true"
            - name: MYSQL_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: MYSQL_DB_HOST
            - name: MYSQL_DB_PLANILLA
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: MYSQL_DB_PLANILLA
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-root-credentials
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root-credentials
                  key: MYSQL_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: planilla-service
  labels:
    app: planilla-service
spec:
  selector:
    app: planilla-deployment
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: LoadBalancer