server:
  port: 8081
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/jaaabby/EV2_Mingeso
          search-paths: config-data
